# ansible-playbook -l live -i hosts deploy.yml

# install nginx
# create/check release folder
# copy public to remote folder
# update nginx config
# restart nginx

- hosts: live
  remote_user: ubuntu
  vars:
    http_port: 80
    release_path: "/home/{{ ansible_ssh_user }}/releases"

  tasks:

  - name: Get time
    shell: "date +%s"
    register: timestamp

  - name: Nginx is present
    sudo: true
    apt: pkg=nginx state=present

  - name: Releases dir exists
    file: state=directory path={{ release_path }}

  - name: Release path exists
    file: state=directory path={{ release_path }}/{{ timestamp.stdout }}/

  - name: Copy local to remote
    copy: src=public/ dest={{ release_path }}/{{ timestamp.stdout }}/

  - name: Update nginx default config
    sudo: true
    template: src=nginx.default.j2 dest=/etc/nginx/sites-enabled/default

  - name: Restart nginx
    sudo: true
    service: name=nginx enabled=yes state=restarted

  - name: Tidy up to last 5 releases
    command: bash -lc "cd {{ release_path }} && rm -rf `ls -t | awk 'NR>5'`"
